### ISSUE TITLE
Unexpected error when using tf-pipeline

### ISSUE THREAD

**Issue by kmanning** [manheim/terraform-pipeline#140]
I have a terraform project I created to verify the library was installed properly and it's throwing an unexpected error.  

```expected to call Jenkinsfile.echo but wound up catching Jenkinsfile.invokeMethod; see: https://jenkins.io/redirect/pipeline-cps-method-mismatches/
[Pipeline] End of Pipeline
java.lang.NullPointerException: Cannot invoke method echo() on null object
    at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
    at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
    at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
    at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
    at Jenkinsfile.invokeMethod(Jenkinsfile.groovy:21)
    at Jenkinsfile.node(Jenkinsfile.groovy:12)
    at TerraformValidateStage.pipelineConfiguration(TerraformValidateStage.groovy:28)
    at TerraformValidateStage.build(TerraformValidateStage.groovy:19)
    at TerraformValidateStage.then(TerraformValidateStage.groovy:11)
    at WorkflowScript.run(WorkflowScript:10)
    at ___cps.transform___(Native Method)
```

the jenkinsfile:
```
// Jenkinsfile
@Library(['terraform-pipeline@v3.10']) _

def validate = new TerraformValidateStage()

def deployNP = new TerraformEnvironmentStage('nonprod')

validate.then(deployNP)
        .build()

```

main.tf
```
terraform {
  required_version = "~> 0.11"
  backend          "s3"             {}
}

variable "region" {
  default = "us-east-1"
}

provider "aws" {
  region  = "${var.region}"
  version = "~> 2.0"
}

data "aws_caller_identity" "current" {}

output "account_id" {
  value = "${data.aws_caller_identity.current.account_id}"
}

output "caller_arn" {
  value = "${data.aws_caller_identity.current.arn}"
}

output "caller_user" {
  value = "${data.aws_caller_identity.current.user_id}"
}



```

the error seems to be pointing to [here](./src/TerraformValidateStage.groovy#L11)

**Comment by kmanning** [comment]
Solution: Pipeline was not initializing the Jenkinsfile object. Eg: Jenkinsfile.init(this, env). As a result, the underlying terraform-pipeline library was failing with a null pointer, as it didn't have a reference to the Jenkinsfile pipeline script.

**Comment by kmanning** [comment]
Closing this - works as designed. But this User Experience could be improved. Opened Issue #141 , and closing this out.
